### ISSUE TITLE
Use PREFIX in Turtle

### ISSUE THREAD

**Issue by rubensworks** [w3c/sparql-update#32]
As suggested by @afs in https://github.com/w3c/sparql-update/pull/31#discussion_r1311608934, we should replace the `@prefix` syntax in Turtle examples to `PREFIX`.

**Comment by niklasl** [comment]
I would prefer `prefix` (lower-case). Argument would be: it's more like "natural writing" (where upper-case is most common for e.g. acronyms/abbreviations, and "shouting"), which Turtle is intentionally designed for; in contrast to SPARQL, which is designed to "feel" like SQL (where the classic norm is upper-case for keywords). 

I am in favour of it in any form due to the increased isomorphism with SPARQL (to e.g. help when copy-pasting between data and queries).
